### ISSUE TITLE
Problems executing  DVBT_TX_Demo flow graph

### ISSUE THREAD

**Issue by hyumavox** [BogdanDIA/gr-dvbt#29]
Hello:
Trying to execute the file I am getting the following error:
<<< Welcome to GNU Radio Companion 3.7.9.2 >>>

Preferences file: C:\Users\user\AppData\Roaming\SPB_Data/.gnuradio/grc.conf
Block paths:
	C:\Users\user\AppData\Roaming\SPB_Data\.grc_gnuradio (C:\Users\user\AppData\Roaming\SPB_Data/.grc_gnuradio)
	C:\Program Files\GNURadio-3.7\share\gnuradio\grc\blocks (C:\Program Files\GNURadio-3.7\bin\..\share\gnuradio\grc\blocks)

Loading: "C:\GNURADIO\dvbt_tx_demo.grc"
>>> Done

Showing: "C:\GNURADIO\dvbt_tx_demo.grc"

Generating: 'C:\\GNURADIO\\top_block.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: C:\Program Files\GNURadio-3.7\gr-python27\python.exe -u C:\GNURADIO\top_block.py

Using Volk machine: avx2
ffC:\GNURADIO	est.ts: Invalid argument
Traceback (most recent call last):
  File "C:\GNURADIO\top_block.py", line 139, in <module>
    main()
  File "C:\GNURADIO\top_block.py", line 134, in main
    tb = top_block_cls()
  File "C:\GNURADIO\top_block.py", line 100, in __init__
    self.blocks_file_source_0 = blocks.file_source(gr.sizeof_char*1, "C:\GNURADIO\test.ts", False)
  File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\blocks\blocks_swig0.py", line 1083, in make
    return _blocks_swig0.file_source_make(itemsize, filename, repeat)
RuntimeError: can't open file
[dvbt_tx_demo.zip](https://github.com/BogdanDIA/gr-dvbt/files/1333336/dvbt_tx_demo.zip)

**Comment by rogergermann** [comment]
same issue here, did you find a solution?

**Comment by rogergermann** [comment]
I had the same error on Ubuntu. The standard path on linux goes to the home direction. Simply set the file source and sink direction manually via clicking on them and navigating to the file
